config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'weather_types#index', as: 'weather_types'
  match '/weathers/songs', :action => 'get_songs', :via => [:get], :controller => 'weather_types', as: 'get_songs'
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :artist
    has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :album
end

app/models/weather_type.rb
class WeatherType < ApplicationRecord
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def index
        @albums = Album.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index

  end

end

app/controllers/weather_types_controller.rb
class WeatherTypesController < ApplicationController
  def index

  end

  def get_songs
    p params[:chosen_weather]
    @songs = Song.all
    redirect_to action: "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<h1>Album</h1>
<% @albums.each do |a| %>
    Album name: <%= a.name %>
<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vivacity</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h1>Songs</h1>
<% @songs.each do |song| %>
  <%= song.name %>
  <br>
<% end %>

app/views/weather_types/index.html.erb
<h1>Weathers</h1>
<%= form_tag(get_songs_path, method: 'get') do %>
  <%= label_tag "songs" %>
  <%= select_tag(
    :chosen_weather,
    options_from_collection_for_select(WeatherType.all, "id", "name")
  ) %>
  <%= submit_tag "Get songs" %>
<% end -%>